name: jurnal_pembelajaran
description: "Aplikasi Jurnal Pembelajaran."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  adaptive_responsive_util: ^1.0.5
  appwrite: ^12.0.4
  auto_size_text: ^3.0.0
  cached_network_image: ^3.3.1
  dio: ^5.5.0
  expandable_text: ^2.3.0
  firebase_core: ^3.1.1
  firebase_analytics: ^11.1.0
  firebase_app_check: ^0.3.0+2
  firebase_crashlytics: ^4.0.2
  firebase_in_app_messaging: ^0.8.0+2
  firebase_messaging: ^15.0.2
  firebase_performance: ^0.10.0+2
  firebase_remote_config: ^5.0.2
  flutter_carousel_widget: ^2.2.0
  flutter_downloader: ^1.11.7
  flutter_inappwebview: ^6.0.0
  flutter_local_notifications: ^17.2.1
  flutter_native_splash: ^2.4.0
  flutter_riverpod: ^2.5.1
  flutter_slidable: ^3.1.0
  flutter_svg: ^2.0.10+1
  flutter_timer_countdown: ^1.0.7
  font_awesome_flutter: ^10.7.0
  freezed_annotation: ^2.4.2
  go_router: ^14.2.0
  google_fonts: ^6.2.1
  group_button: ^5.3.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  jiffy: ^6.3.1
  json_annotation: ^4.9.0
  loading_animation_widget: ^1.2.1
  logger: ^2.3.0
  path: ^1.9.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.1.0
  riverpod_annotation: ^2.3.5
  upgrader: ^10.3.0
  url_launcher: ^6.3.0
  uuid: ^4.4.0
  video_player: ^2.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  flutter_gen_runner: ^5.6.0
  flutter_launcher_icons: ^0.13.1
  freezed: ^2.5.2
  hive_generator: ^2.0.1
  hive_test: ^1.0.1
  json_serializable: ^6.8.0
  retrofit_generator: ^8.1.1
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/logo_icon_ika.png"
  min_sdk_android: 21

flutter_gen:
  line_length: 80
  integrations:
    flutter_svg: true
